### ISSUE TITLE
Using vl-interaction-select to select feature from pbf vector tiles

### ISSUE THREAD

**Issue by jmpmcmanus** [ghettovoice/vuelayers#119]
Your demo has been very helpful in setting up my project. However, I have not been able to use vl-interaction-select to select features from pbf vector tiles. Looking at the code for vl-interaction-select it looks like it expects geojson data. Is this correct? Is there a way of using vl-interaction-select as in your demo, but for pbf vector tiles? 

Thanks!
Jim

**Comment by ghettovoice** [comment]
Hi @jmpmcmanus ,
`vl-interaction-select` intended for use with any vector layer, i.e. layer created with `vl-layer-vector`.
Since you are work with vector tiles, I suppose you are using `vl-layer-vector-tile` to render them, so `vl-interaction-select` doesn't handle.  

With vector tiles layer (and any other tile layer) you should listen for map click event and  use pixel coordinates or geographical coordinates to search features.  
Take a look for this jsfiddle I had made https://jsfiddle.net/ghettovoice/jy3Lr0bd/, it is one-to-one translation of the official OpenLayers example http://openlayers.org/en/latest/examples/vector-tile-selection.html

**Comment by jmpmcmanus** [comment]
Thanks for the quick reply, and links!
    On Sunday, December 16, 2018, 3:00:18 PM EST, Vladimir Vershinin <notifications@github.com> wrote:  
 
 
Hi @jmpmcmanus ,
vl-interaction-select intended for use with any vector layer, i.e. layer created with vl-layer-vector.
Since you are work with vector tiles, I suppose you are using vl-layer-vector-tile to render them, so vl-interaction-select doesn't handle.

With vector tiles layer (and any other tile layer) you should listen for map click event and use pixel coordinates or geographical coordinates to search features.
Take a look for this jsfiddle I had made https://jsfiddle.net/ghettovoice/jy3Lr0bd/, it is one-to-one translation of the official OpenLayers example http://openlayers.org/en/latest/examples/vector-tile-selection.html
