### ISSUE TITLE
how to create new point by client

### ISSUE THREAD

**Issue by r3j3c73d** [ghettovoice/vuelayers#120]
Hi, I'm beginner in vue and also using the vuelayers, so sorry for my newbies questions.
I uses vuelayers in my project and show basic map without any other options.
I want to show a point with custom style (i saw other issues about style points) but i need that when user click on it, i save the location, but i have no idea what should i do. also i was read docs but vl-geom-point is empty so i can't read about it. can you help me and show me the right path? thanks

my purpose is that i can get geometry location for my source and destination that user choose them.
thanks

**Comment by ghettovoice** [comment]
Hi @r3j3c73d ,
no problem, while documentation isn't ready, I'll try to ask as fast as possible.

There are several ways to add and style point (or any other geometry feature)  to the map. Each would fit for it use case.

The simplest case is just a vector layer with any type of features can be implemented just with `vl-feature` with `vl-style-box` components. Take a look here https://jsfiddle.net/ghettovoice/jebLac2y/  
Short explanation: for vector layers to detect feature selection you can use `vl-interaction-select` that has synchronizable property `feature` in which you will get current selected feature(s) (`selected` data property in my example). You can use vue watcher to react on the updates of it.

Another case is detecting click on the map for tile layers, this can be done like in this example https://jsfiddle.net/ghettovoice/jy3Lr0bd/.   
Note that here I use `vl-style-func` component instead of `vl-style-box` because defining layer style allows you apply styling dynamically (per feature, or some other conditions).

To show just a one marker there is exists also simplified way (current geolocation, address & etc.): 

```html
<vl-map>
  <vl-feature id="my-locatoin">
    <vl-geom-point :coordinates="[10, 10]"></vl-geom-point>
   <vl-style-box>
     ...
   </vl-style-box>
  </vl-feature>
</vl-map>
```

When you add feature directly to the `vl-map` component it will be rendered in the internal map overlay  layer, i.e. always on top other  layers. Good demonstration of this use case you can find in the official demo app https://github.com/ghettovoice/vuelayers-demo/blob/master/src/App.vue#L66

**Comment by r3j3c73d** [comment]
Thank you very much, i think, i need to change features.geometry.coordinates dynamically, do you have any suggestion? it's so newbie question sorry

**Comment by ghettovoice** [comment]
Currently there is a bug in the `vl-source-vector` watcher for `features` property, it should be fully synchronizable but now taking into account only add/removed features.  

So to workaround it you can add features to source with `vl-feature` component.  
Here is the updated example https://jsfiddle.net/ghettovoice/vuo97yn3/ with coordinates changes during runtime.

**Comment by r3j3c73d** [comment]
Hi, thank you very much for your explanations. It's take my time very much cause i'm not good enough in vue.js to figure out what should i need to do. but i can't implement what i want, can you help me on it? i just want to get source and destination location from map and show it to my user :( i'm so sorry for my dummy questions

**Comment by ghettovoice** [comment]
Hi @r3j3c73d ,
sorry for the late response, I was busy at holidays.

I didn't fully understand what actually you can't implement. If you explain me more deeply your use case I'll try to help you. Or show me you current source code so I can see what you trying to implement.

As for my last example  https://jsfiddle.net/ghettovoice/vuo97yn3/, it emulates simplest use case:
you app loads features from some remote backend, then renders them on the map.
