### ISSUE TITLE
different interaction-select for pointerMove and simpleclick.

### ISSUE THREAD

**Issue by marena** [ghettovoice/vuelayers#151]
Hi,

I'm trying to create different interaction for pointerMove and simpleclick.

I tried to add two vl-interaction-select, but it does not work.

Any way to do this?

**Comment by ghettovoice** [comment]
Hi @marena ,
multiple select interaction shouldn't be used at the same time, because there is race condition which one handles user input.
To change select interaction behavior you can use the `condition`  property that accepts function that returns bool to indicate whether that event should be handled.

```html

<template>
  <button @click="selectByHover = !selectByHover">Select by {{ !selectByHover ? 'hover' : 'click' }}</button>

  <vl-map ...>
     ....
     <vl-interaction-select  :condition="selectCondition" :features.sync="selectedFeatures" />
  </vl-map>
</template>

<script>
  import * as eventCondition from 'ol/events/condition'

  export default {
   ....
    computed: {
        selectCondition () {
           return this.selectByHover ? eventCondition.pointerMove : eventCondition.singleClick
        },
    },
    data () {
      return {
        ...
        selectedFeatures: [],
        selectByHover: false,
      }
    },
  }
</script>
```

**Comment by marena** [comment]
Thanks for replay,

so best way is use vl-interaction for select and for tooltip https://github.com/ghettovoice/vuelayers/issues/84
