### ISSUE TITLE
Meters to pixels or pixels to meters

### ISSUE THREAD

**Issue by mustafahamid** [ghettovoice/vuelayers#162]
Hi, 
 what is the relation between meter and pixel in vuelayers. I mean if  vl-geom-circle with  radius="5"  ,  is 5 represents pixels or meters ?.

**Comment by ghettovoice** [comment]
Hi @mustafahamid ,
usually this relation is defined in the projection and used for resolution calculation. You can find point resolution (i.e. relation between pixels and meters) with this function from openlayers api https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.getPointResolution.

But as for styles, there all properties like `radius`, `offsets` and etc are measured in pixels. This is due to styles rendering handled with plain canvas context (for canvas renderer).
Hope this help
