### ISSUE TITLE
which is more performant, using OGC service like  WFS  or GeoJSON?

### ISSUE THREAD

**Issue by boussadjra** [ghettovoice/vuelayers#168]
I'm developing an application using PostGIS, Laravel and Vuelayers, for the moment Laravel serves me the data using GeoJSON format that i receive it in front-end and i render it using `vl-feature` component, the size of received data is >500KB which would reach 25MB in future, i predict that could affect the application performance, and i read that using OGC service like WMS would be more efficient. what do you think?

**Comment by ghettovoice** [comment]
Hi @boussadjra,
if you work with big layers, I suggest you do not use `vl-feature` for this, because there Vue reactivity slows down performance. You can work with features just as simple array of plain objects (features re-presented as GeoJSON). `vl-source-vector` has property `features` through which you can add features to the layer.
Also `vl-source-vector` can load features by the url from some remote OGC service like WFS.

Which one to use WFS or WMS is strongly related to your use case: if you need just show a lot of geo objects - WMS would be nice, good load speed, low memory usage. But if you need some interaction with this objects, WMS can be a bit harder to use. For example you need to highlight clicked feature, with pure WMS it is impossible. But you can combine WMS as base layer with additional requests to backend when feature clicked that returnes clicked feature geometry, then you can overlay it with vector layer

**Comment by boussadjra** [comment]
Thank you very much for your advice and for this awesome library, i hope that you could add the missing documentation like in `https://vuelayers.github.io/#/docs/component/wms-source` section
