### ISSUE TITLE
What is the purpose of vl-style-circle?

### ISSUE THREAD

**Issue by categulario** [ghettovoice/vuelayers#204]
As part of an additional effort to complete the docs I'm writing documentation for all of the style components but couldn't understand the meaning and usage of `vl-style-circle`. What I understand is that I can use `stroke-style` and `fill-style` to style the circle. Also the only property of `vl-style-circle` is radius, which is set in the geometry.

Any advice?

**Comment by ghettovoice** [comment]
Hello @categulario ,
`vl-style-circle`(based on the `ol/style/Circle` https://openlayers.org/en/latest/apidoc/module-ol_style_Circle-CircleStyle.html) component actually is the special shortened version of more complex style component `vl-style-reg-shape` (based on the `ol/style/RegularShape` https://openlayers.org/en/latest/apidoc/module-ol_style_RegularShape-RegularShape.html) .
It here as a separate component because it is common case to use circles with stroke/fill for point layers.

**Comment by categulario** [comment]
Do you mind giving me an usage example for `vl-style-circle`? I'm still not sure how to use it.

Thanks!

**Comment by categulario** [comment]
Do you mind giving me an usage example for `vl-style-circle`? I'm still not sure how to use it.

Thanks!

**Comment by ghettovoice** [comment]
Sure. Take a look here https://jsfiddle.net/ghettovoice/z6huwdcs/
Points are styled as circles with `vl-style-circle`, but the square is simply styled  by stroke and fill.

**Comment by categulario** [comment]
Thanks!
