### ISSUE TITLE
Why is view's @zoom rounded?

### ISSUE THREAD

**Issue by keeganwitt** [ghettovoice/vuelayers#216]
Cytomine uses `<vl-view :zoom.sync="zoom" />` (see https://github.com/Cytomine-ULiege/cytomine-frontend/blob/master/src/components/Explore/Viewer.vue#L14), to get the current zoom level, then uses that number to compute other values displayed. For example, the magnification on a scale line (see https://github.com/Cytomine-ULiege/cytomine-frontend/blob/master/src/components/Explore/ScaleLine.vue#L39).

The way this currently works (and I don't know if it's what @urubens intended or not), is that if you are zooming within the same level, the scale doesn't change until you hit the threshold of the next level.  This is because the value returned by VueLayers' zoom is rounded.  Is there a reason for this?  We had to pull the unrounded zoom out with `this.$refs.olview.$view.getZoom()` rather than using the built-in functionality of VueLayers.  I saw previously the code was using `Math.ceil()`.

**Comment by ghettovoice** [comment]
Hello @keeganwitt ,
I actually can't remember why I use rounding with zoom. I only remember that there was some issues with fractional zoom, but this was around year ago. Since that openlayers was upgraded up to the v5.

I currently have tested zooming without rounding I haven't experienced any issue.
So I think I can remove rounding in the next release
