### ISSUE TITLE
Problem with vl-style-icon

### ISSUE THREAD

**Issue by MaximeStl** [ghettovoice/vuelayers#223]
Hi, I try to use vl-style-icon but nothing work in my case, need some help ?
            <vl-layer-vector :z-index="vectorZIndex">
                            <vl-source-vector ref="parcellesSrc" :features="parcelles"></vl-source-vector>
                            <vl-style-box>
                                <vl-style-fill  color="#4CAF50AA"></vl-style-fill>
                                <vl-style-stroke color="#4CAF50" :width="3"></vl-style-stroke>
                                <vl-style-icon src="https://maps.google.com/mapfiles/kml/shapes/gas_stations_maps.png"></vl-style-icon>
                            </vl-style-box>
                        </vl-layer-vector>

**Comment by MaximeStl** [comment]
<vl-layer-vector :z-index="vectorZIndex">
                            <vl-source-vector ref="parcellesSrc" :features="parcelles"></vl-source-vector>
                            <vl-style-box>
                                <vl-style-fill  color="#4CAF50AA"></vl-style-fill>
                                <vl-style-stroke color="#4CAF50" :width="3"></vl-style-stroke>
                                <vl-style-icon src="https://maps.google.com/mapfiles/kml/shapes/gas_stations_maps.png"></vl-style-icon>
                            </vl-style-box>
                        </vl-layer-vector>

**Comment by ghettovoice** [comment]
Hello @MaximeStl ,
thanks for response!
From your example: what feature types in the `parcelles` array you have? Is polygons, lines or points?

**Comment by MaximeStl** [comment]
Hi, 
It's polyons.

**Comment by ghettovoice** [comment]
Obviously polygons can't be styled with `vl-style-icon` by default, because `vl-style-icon` and `vl-style-circle` actually bounds to some single point.
To style polygons, lines with `vl-style-icon` you should transform them to the point geometry before. This can be done on the styling layer with geometry override. But you should use `vl-style-func` (i.e. style function) instead of separate style components.
Here is example https://jsfiddle.net/ghettovoice/1s3fugb9/
Take a note that helpers from `VueLayers.olExt` namespace from this example available here only in the UMD build. With ES modules you can import them from `vuelayers/lib/ol-ext` directory like:
```
import { findPointOnSurface } from 'vuelayers/lib/ol-ext'
```

**Comment by MaximeStl** [comment]
Hello @ghettovoice ,
Thanks for this awesome response ! Problem resolved :)
