### ISSUE TITLE
Vector Tile feature selection not working as intended

### ISSUE THREAD

**Issue by colinbarber** [ghettovoice/vuelayers#235]
Hi there, I'm working off of the vuelayers demo, using vuelayers@next and noticed that when a feature is clicked on on the Vector Tile layer, it is not selected until the map is moved. Likewise, it is not deselected when clicking away from the feature until the map is moved.

This behaviour can also be replicated in the demo application page on the official site.
( https://vuelayers.github.io/demo/ )

I would like to know how to modify the code so that:

1. the feature is selected upon clicking, and
2. a popup appears for the selected feature, as seen in a normal vector layer.

**Comment by colinbarber** [comment]
upon further inspection, once a vector tile layer feature is selected in the demo app, it breaks feature selection for all layers in the same way. 

there is an error in events.js, here is the log:

Uncaught TypeError: target.addEventListener is not a function
    at listen (events.js?1e8d:174)
    at VectorSource.setupChangeEvents_ (Vector.js?5831:331)
    at VectorSource.addFeatureInternal (Vector.js?5831:307)
    at VectorSource.addFeature (Vector.js?5831:290)
    at VectorSource.eval (Vector.js?5831:452)
    at Collection.boundListener (events.js?1e8d:41)
    at Collection.dispatchEvent (Target.js?0ec0:99)
    at Collection.insertAt (Collection.js?e300:179)
    at Collection.push (Collection.js?e300:204)
    at Collection.extend (Collection.js?e300:116)

**Comment by colinbarber** [comment]
Following the suggestion proposed in this comment here:

https://github.com/openlayers/openlayers/issues/7235#issuecomment-328084600

I was able to fix the bug by modifying lib/ol-ext/format.js and adding the lines

import Feature from 'ol/Feature';
...
function createMvtFmt(options) {
  return new MVT({featureClass: Feature});
}

I'm not sure how you would like me to format a pull request seeing as the options variable is no longer used here, but let me know.

**Comment by ghettovoice** [comment]
Hello @colinbarber ,
sorry for the late response. 
You have made great investigation. I didn't know about this before, thanks!

As for using of custom MVT format instance, right now you can set custom format factory through `format-factory` property of the `vl-source-vector-tile` component https://github.com/ghettovoice/vuelayers/blob/master/src/component/vector-tile-source/source.vue#L18.
Including this as default format, I think, not needed, because this non-rare use case to select underlying features. Also it can decrease rendering performance.

There is also another way to hit the features by the click event: listen for `click` or `singleclick ` event on the `vl-map` component and make searching of the features at the pixel.
Here is adapted for VueLayers example taken from OpenLayers Examples page:
- for VueLayers https://jsfiddle.net/ghettovoice/gp3dwjot/
- for OpenLayers https://openlayers.org/en/latest/examples/vector-tile-selection.html

**Comment by jmpmcmanus** [comment]
I have a vector tile layer and am getting the Uncaught TypeError: target.addEventListener is not a function error with trying to select a feature. 

I'm using method shown in VueLayers https://jsfiddle.net/ghettovoice/gp3dwjot/ but am still getting the error. I'm listening for a single click in vl-map:

    <vl-map v-if="mapVisible" class="map" ref="map" :load-tiles-while-animating="true" :load-tiles-while-interacting="true"
      @singleclick="onMapClick" data-projection="EPSG:4326" @mounted="onMapMounted" :controls="false" style="height:1200px">

The vector tile layer looks like:

      <vl-layer-vector-tile ref="vectorTileLayer">
        <vl-source-vector-tile :url="url"></vl-source-vector-tile>
        <vl-style-func ref="layerStyle" :factory="g

etncwellwiseMaxStyle"></vl-style-func>
      </vl-layer-vector-tile>

and onMapClick uses getFeaturesAtPixel:

    onMapClick: function (event) {
      let pixel = event.pixel
      let features = this.$refs.map.$map.getFeaturesAtPixel(pixel)

Is there something I'm missing?

I've also tried the other method of using format-factory, but have not figured out how to implement it. Could you show me an example?

Thanks
Jim

**Comment by ghettovoice** [comment]
@jmpmcmanus can you provide error stack trace. Looking at your code parts I can't currently reproduce such error

**Comment by jmpmcmanus** [comment]
The error output is:

Uncaught TypeError: target.addEventListener is not a function
    listen events.js:174
    setupChangeEvents_ Vector.js:331
    addFeatureInternal Vector.js:307
    addFeature Vector.js:290
    bindFeaturesCollection_ Vector.js:452
    boundListener events.js:41
    dispatchEvent Target.js:99
    insertAt Collection.js:179
    push Collection.js:204
    extend Collection.js:116
    handleEvent Select.js:432
    handleMapBrowserEvent PluggableMap.js:931
    boundListener events.js:41
    dispatchEvent Target.js:99
    clickTimeoutId_ MapBrowserEventHandler.js:133
    setTimeout handler*emulateClick_ MapBrowserEventHandler.js:129
    handlePointerUp_ MapBrowserEventHandler.js:175
    boundListener events.js:41
    dispatchEvent Target.js:99
    fireNativeEvent PointerEventHandler.js:393
    pointerUp NativeSource.js:64
    eventHandler_ PointerEventHandler.js:199
    boundListener events.js:41
    listen events.js:174
    addEvents_ PointerEventHandler.js:210
    addEvents_ PointerEventHandler.js:209
    register_ PointerEventHandler.js:174
    registerSources PointerEventHandler.js:141
    PointerEventHandler PointerEventHandler.js:115
    handlePointerDown_ MapBrowserEventHandler.js:217
    boundListener events.js:41
    dispatchEvent Target.js:99
    fireNativeEvent PointerEventHandler.js:393
    pointerDown NativeSource.js:44
    eventHandler_ PointerEventHandler.js:199
    boundListener events.js:41
    listen events.js:174
    addEvents_ PointerEventHandler.js:210
    addEvents_ PointerEventHandler.js:209
    register_ PointerEventHandler.js:174
    registerSources PointerEventHandler.js:141
    PointerEventHandler PointerEventHandler.js:115
    MapBrowserEventHandler MapBrowserEventHandler.js:78
    PluggableMap PluggableMap.js:288
    Map Map.js:75
    createOlObject index.js:187

At the bottom there is a link named "Learn More"  which sends you to the following page:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function

Jim

**Comment by ghettovoice** [comment]
Do you also have vl-interaction-select enabled in this map? If so you need to filter out vector tile layers from it with `layers` prop or through custom `filter`. There is also an option to provide custom format reader to the vl-source-vector-tile that will can create instances of `ol/Feature` instead of `ol/renderer/Feature`, but I guess this can lead to performance decrease.
https://github.com/openlayers/openlayers/issues/9840

So the best way I think is filter out vector tile layers from select interaction and use select/unselect through singleclick/click map events (that is how it is implemented in my demo and suggested by the openlayers team).

Filter by layer names. only defined layer names will be selectable
```
<vl-interaction-select :layers="['layer_1', 'layer_2', ....]">
```

Filter by layer with custom callback
```
import { VectorTile } from 'ol/layer'
...
<vl-interaction-select :layers="layer => !(layer instanceof VectorTile)">
```

Filter by feature + layer
```
import { Feature } from 'ol'
...
<vl-interaction-select :filter="(feature, layer) => feature instanceof Feature">
```

**Comment by jmpmcmanus** [comment]
I have vl-interaction-select enabled in this map. I'm trying to use it to select features which are from vector tile map layers. I my not understand your comment above, but are you telling me to filter out features which are part of vector tile layers? I need to be able to select those.

I tried the method described above by colenbarber and it worked except shifted the map location to null island. I would like to try the method you described above using format-factory. I've not figured out how to implement that. Could you show me an example?

Thanks
Jim

**Comment by ghettovoice** [comment]
There was a bug in the vuelayers when using ol/Feature as class for vector tile feature. But it should be resolved in the latest v0.11.33.

With custom format reader factory:

```html
<template>
  ...
  <vl-source-vector-tile :format-factory="createMvtFormat" />
</template>

<script>
import { Feature } from 'ol'
import { MVT } from 'ol/format'

export default {
  methods: {
    createMvtFormat () {
      return new MVT({
        featureClass: Feature,
      })
    },
  },
}
</script>
```

With such configured MVT format it should now create ol/Feature instances instead of ol/renderer/Feature. So now features from vector tile layer should be selectable by vl-interaction-select. But take a note that these feature be splitted by tiles

**Comment by jmpmcmanus** [comment]
That got rid of the error, but it changes the location to null island. The null island location is the default location if you do not specify a location, so it seems to be setting the location back to the default. Any ideas of why this is happening?

I also looked at the filtering methods you described. I'm using vl-interaction-select to select a feature, which is in a vector tile layer, highlight the feature, and display data from the feature in a popup. If I filter out features which are from vector tiles layers, then the feature is not highlighted, and the popup is not launched. Possibly if there is a way of selecting a feature from the vector tile layer, and converting the feature from vector tile layer to just a vector layer, this would eliminate the error?

**Comment by ghettovoice** [comment]
> Possibly if there is a way of selecting a feature from the vector tile layer, and converting the feature from vector tile layer to just a vector layer, this would eliminate the error?

This is now supported use case, see my last example above. MVT format that is used to read features from vector tiles creates simple vector features that can be selected by vl-interaction-select as any other feature from vector sources.

> That got rid of the error, but it changes the location to null island. The null island location is the default location if you do not specify a location, so it seems to be setting the location back to the default. Any ideas of why this is happening?

Sorry, I don't get this. Do you talking about map view center? And at which moment you see this behaviour?
