### ISSUE TITLE
geometries redrawn every time the map moves

### ISSUE THREAD

**Issue by SSepton** [ghettovoice/vuelayers#261]
i have tried drawing some geometries on the map and i noticed that the map started to slow,
when i checked the issue with a plane openlayers project the issue did not appear.
i tired to debug your code and found out that every time i move the map or zoom in and out the getCoordinates and setCoordinates function are being invoked, i presume that's because the geometries are redrawn, and as a result the map is getting very slow when a relatively small amount of geometries are drawn.

is there any way to fix it? maybe draw the geometry only when the component is created and not change it every time?

**Comment by ghettovoice** [comment]
Hello @SSepton ,
I guess you are using `vl-feature` and `vl-geom-*` components, right?
They are not so good when you have a lot of features on the map. Current version of Vue doesn't allow fully virtual components without binding to some DOM element, so a lot of changes lead to a lot of DOM changes that is obviously very slow. And when you use plane OpenLayers you haven't that overhead from Vue templates. 

I can suggest you to switch to use `vl-layer-vector`, `vl-source-vector` and define features as array through `features` property.

Anyway can you dump here part of your map component to clarify things? I ask you because triggering of static geometries on move zoom usually shouldn't be executed. It can be when for examples features be out of view and then you move the map to this feature.

**Comment by SSepton** [comment]
Thanks! 
The problem is actualy when i used the `vl-feature` and `vl-geom-*` ill try to expolre the option of using `vl-source-vector` and `vl-layer-vector`.
The getters and setters triggering are probably because of the features moving out of view and then returning to view again... But i assume that this problem will be gone when i use the features array in the  `vl-source-vector`.

**Comment by SSepton** [comment]
After further investigating i noticed that the features option in `vl-source-vector` gets an array in GeoJSONFeature format, and circles can't be drawn in this format. Is there any way to draw circle polygons through the features attribute?

**Comment by ghettovoice** [comment]
Yes, you are right, GeoJSON spec doesn't support circle geometries. But you can represent circles as circular polygons.

To build circular polygons, I can suggest you two options: 
- with plane GeoJSON you can use turf helpers http://turfjs.org/docs/#circle
- with OpenLayers feature objects you can use https://openlayers.org/en/v5.3.0/apidoc/module-ol_geom_Polygon.html#.circular
