### ISSUE TITLE
Distorted Layer Drawing

### ISSUE THREAD

**Issue by SSepton** [ghettovoice/vuelayers#266]
I am working on a map project who is focused around the parts of the middle east and europe, and i noticed that when drawing features through the `vl-layer-vector` component (as you reccomended in issue no. #261 ) the geometries are getting distorted. it is noticeable when trying to draw circles (that eventually are drawen as ellipses because of the distortion) in the coordinates around [30,40]. (when trying to draw on [0,0] everything is as expected). 
after further investigating i discovered that the distortion is not only on the features drawen on the map, its actually on the map layer itself! even the map layer is stretched and distorted (in compare to pure openlayers object i have opened to test the differences).
by the way, the distortion i happening only on the map layers and not when trying to draw geometries with the `vl-feature` and `vl-geom-*` components. 
here are some code samples:
the distorted layers:
```
<template>
  <div style="height: 95vh">
    <vl-map data-projection="EPSG:4326" style="height: 100%">
      <vl-view :zoom.sync="zoom" :center.sync="center"></vl-view>

      <vl-layer-tile>
        <vl-source-osm></vl-source-osm>
      </vl-layer-tile>

      <vl-layer-vector :z-index="1" render-mode="image" :update-while-animating="true">
        <vl-source-vector :features.sync="features"></vl-source-vector>
      </vl-layer-vector>
    </vl-map>
  </div>
</template>

<script>
import {Circle} from 'ol/geom';
import {fromCircle} from 'ol/geom/Polygon';
  export default {
    data () {
      return { 
        zoom: 3,
        center: [10, 10],
        features: [],
      }
    },
    mounted() {
      this.features.push({
                type: "Feature",
                geometry: {
                  type: 'Polygon',
                  coordinates: fromCircle(new Circle([30,40], 12), 360).getCoordinates()
                }
              });
    }
  }
</script>
```

same action on other map location (notice the only difference is the circle coordinates): 
```
<template>
  <div style="height: 95vh">
    <vl-map data-projection="EPSG:4326" style="height: 100%">
      <vl-view :zoom.sync="zoom" :center.sync="center"></vl-view>

      <vl-layer-tile>
        <vl-source-osm></vl-source-osm>
      </vl-layer-tile>

      <vl-layer-vector :z-index="1" render-mode="image" :update-while-animating="true">
        <vl-source-vector :features.sync="features"></vl-source-vector>
      </vl-layer-vector>
    </vl-map>
  </div>
</template>

<script>
import {Circle} from 'ol/geom';
import {fromCircle} from 'ol/geom/Polygon';
  export default {
    data () {
      return { 
        zoom: 3,
        center: [10, 10],
        features: [],
      }
    },
    mounted() {
      this.features.push({
                type: "Feature",
                geometry: {
                  type: 'Polygon',
                  coordinates: fromCircle(new Circle([0,0], 12), 360).getCoordinates()
                }
              });
    }
  }
</script>
```

**Comment by SSepton** [comment]
I have solved the problem by adding another projection value in the `vl-view` component (im using a map with 'EPSG:4326' projection). for some reason when i set the projection in the `Vue.use()` section its not enough to fix all of the distortion issues from changing the map units, and you need to also set it in the `vl-view` component

**Comment by ghettovoice** [comment]
Hello @SSepton ,
as you already found such distortion is the result of representation of the circular polygon in view projection, actually when the view projection for example EPSG:4326 you will get also distortion of the tile layers near the earth poles.

In the VueLayers there are two projections are used, so called `data-projection` (it can be defined globally in Vue.use call or on the `vl-map` cmp) and `vl-view` projection.
So:
- view projection is the actual inner map view projection that will be used by the openlayers lib to render your map, all layers will be reprojected to it at the render time
- data projection is the projection at the VueLayers level, i.e all raw coordinates will use this projection, and when they are passed to the openlayers, they will be reprojected to view projection.

So such distortion you get due to using of 'EPSG:4326' projection as a data projection. To avoid this you can you 'EPSG:3857'  for data coordinates. There are two options:

- remove `data-projection` from the `vl-map` tag https://jsfiddle.net/ghettovoice/zh8kwu6j/
- set another projection on the `vl-source-vector` https://jsfiddle.net/ghettovoice/1dqpu5kn/

Result will be the same, you get your circles (or any other polygons) without distortion by reprojection from EPSG:4326 to EPSG:3857
