### ISSUE TITLE
Control Layers

### ISSUE THREAD

**Issue by josejachuf** [ghettovoice/vuelayers#307]
Hi. This is my first message around here.

I am writing a series of short articles about connecting to geoservices using the quasar framework [1] (this one uses vuejs) with Vuelayers and Vue Leaflet [2].

I have a question about Vuelayers (and with openlayers too), surely when I advance some more will arise
1) Is there a control similar to Leaflet Control.Layers (and Vue Leaflet) that allows me to hide / show layers? If not, how is this resolved?

[1] https://quasar.dev/
[2] https://vue2-leaflet.netlify.com/

**Comment by ghettovoice** [comment]
Hello @josejachuf ,
you are welcome for any question. I'm always trying to answer on each as soon as possible.

Regard to your question: VueLayers doesn't provide any UI components for layers control. But this should be a big problem to implement it by yourself, because all is you need is an array of layers options, that is used to render checkboxes in the menu and `vl-layer-*` components.
There is a main VueLayers demo https://vuelayers.github.io/demo/ (https://github.com/ghettovoice/vuelayers-demo) where this idea is implemented.

BWT strictly speaking Vue Leaflet don't implement any UI control too, it just wraps all available controls from Leaflet. I have a task for wrapping openlayers controls too on my roadmap, but anyway OpenLayers don't provide such control from the box. There is exists an a big extension library for OpenLayers https://viglino.github.io/ol-ext/ that provide such control, and it can be integrated with VueLayers too (currently a bit ugly, but it works).

**Comment by josejachuf** [comment]
Thanks @ghettovoice 
It is true, the one with vue-leaflet comes from the leaflet itself
Best Regards
