### ISSUE TITLE
loader wms getfeatureinfo

### ISSUE THREAD

**Issue by gkvoelkl** [ghettovoice/vuelayers#310]
Hello,

I am a vue newbie.

vuelayers and wms works very well. 

Then I tried to load featureInfo

` let url = element.getFeatureInfoUrl(evt.coordinate)  
       if (url){  
         fetch(url,{  
                        credentials: 'same-origin',  
                        mode: 'cors',  
                    })  
         .then(function(response){ return response.text()})  
         .then(function(html){console.log(html)}  )   
       }   
      })  
`
I got an error message

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource`

The wms service works with the same resource.

Is there a wms-service loader?

Can I load wms-feature info with vuelayers?

Thanks.

Best regards

**Comment by ghettovoice** [comment]
Hello @gkvoelkl ,
this errors is not related to vuelayers itself, because you execute request by yourself with `fetch` call.
Anyway it looks like you trying to make request from one origin to another, also in `cors` mode, and probably the server doesn't return required headers (`Access-Control-Allow-Origin` and so on) or value doesn't allow match to the expected. 
I can only suggest try to disable cors, i.e. set `mode: 'no-cors'`

**Comment by gkvoelkl** [comment]
Thanks.

As far as I understand there is no component in vuelayers for fetching getfeatureinfo and you are not planing to do one.

vuelayers is great work.

Best regard

Gerhard

**Comment by ghettovoice** [comment]
Yes, no special component for fetch. And I don't see any needless for it, because it currently pretty easy to make. As for parsing WMS responses you can use parser from OpenLayers, there is for GetFeatureInfo https://openlayers.org/en/v5.3.0/apidoc/module-ol_format_WMSGetFeatureInfo.html

**Comment by gkvoelkl** [comment]
Thanks for help.

Now I use a proxy and get no more errors.

Best regards
Gerhard

**Comment by ghettovoice** [comment]
Yep, proxy can be a solution too
