### ISSUE TITLE
Add bing source property for centerPoint

### ISSUE THREAD

**Issue by fnoop** [ghettovoice/vuelayers#41]
As per https://msdn.microsoft.com/en-us/library/ff701716.aspx, in order to use BirdsEye imagery set you need to set centerPoint.

**Comment by ghettovoice** [comment]
As I can see official OpenLayers `ol.source.BingMaps` doesn't support this, so there should to be custom implementation. I need to investigate this.

**Comment by ghettovoice** [comment]
I read Imagery API docs about centerPoint and also found a topic about integration BirdsEye imagery to OpenLayers on stackoverflow https://stackoverflow.com/questions/38340011/openlayers-with-bings-bird-eye-view, that describes why it is not supported by OpenLayers.
Briefly BirdsEye imagery has a specific tile system, that can't be implemented without using Bing Maps lib.

So i close this because implementation is out of responsibility of VueLayers package
