### ISSUE TITLE
set extent to ZoomtoExtent control

### ISSUE THREAD

**Issue by npltr62** [ghettovoice/vuelayers#473]
How  setting extent in ZoomtoExtent control dynamically?
`                let extent = this.$refs.vectorSource.$source.getExtent();
               this.$refs.map.$map.getControls()`

**Comment by ghettovoice** [comment]
Hello @npltr62 ,
as I know ZoomToExtent control doesn't allow change extent in runtime, because it can be configured only through control constructor.
Seems that you need to make it yourself or extend their control with additional setter. 

https://github.com/openlayers/openlayers/blob/v6.12.0/src/ol/control/ZoomToExtent.js#L28
