### ISSUE TITLE
`zDirection` for `vl-source-wmts`

### ISSUE THREAD

**Issue by marena** [ghettovoice/vuelayers#477]
Hi @ghettovoice 

Before I dive into deep. Accept `vl-source-wmts` zDirection prop?  I'm playing with this parameter but nothing change.

here is demo https://codesandbox.io/s/nice-raman-v378bm?file=/src/App.vue. In zoom 8 and 9 and south part of czech republic serve tile in another zoom (right zoom) than notth part.

Thanks for answer.

**Comment by ghettovoice** [comment]
Hello @marena ,
for some reason I excluded this option from `vl-source-wmts`. I don't remember, probably because it was not used in ol/source/WMTS constructor several version ago. So for now it is not passed to openlayers and don't work in vl-source-wmts source.
Anyway now I see that it used and should be definitely added. Thanks for report!

**Comment by marena** [comment]
Thanks  for answer. You did a great job with the Vuelayers.

**Comment by ghettovoice** [comment]
It is fixed in v0.12.1

**Comment by marena** [comment]
Great, thanks
