### ISSUE TITLE
cannot build new project

### ISSUE THREAD

**Issue by infokartasplit** [ghettovoice/vuelayers#509]
```
git clone --recursive -j8 https://github.com/ghettovoice/vuelayers.git
cd vuelayers

# install dependencies
npm install

# serve with hot reload at localhost:8080
npm start

# build for production
npm run build

# run unit tests
npm run test:unit

# run e2e tests
npm run test:e2e

# run all tests
npm test
```
npm install reports conflicts

if i npm install --force it installs node_modules but it  reports errors that it cant load stuff from @types/ol
it doesnt work.

**Comment by ghettovoice** [comment]
Hello @infokartasplit 
There was an issue with dropped out enum types in the `ol` package.
The issue has fixed in v0.12.4, upgrade pls.

NOTE: if you want build vuelayers from sources, currently you should use `--legacy-peer-deps` with `npm install`/`npm update` commands, because some of dependencies are compatible but still have an old peer requirements.
