### ISSUE TITLE
How to add custom source OSM ?

### ISSUE THREAD

**Issue by rSammy** [ghettovoice/vuelayers#70]
Hello,

I want to store tiles locally so they can be accessed faster, if not exists I'll just point on openstreetmap servers to get them.

However I first need to add some custom source and add it as a component.
`<vl-custom-source></vl-custom-source>`

**Comment by ghettovoice** [comment]
Hi @rSammy , for the custom XYZ tile layers the best option is to use `vl-source-xyz` (other predefined tile layers actually are based on it).
Currently it is not covered in docs, but you can use this https://github.com/ghettovoice/vuelayers/blob/master/src/mixin/tile-source.js#L18 as a hint for acceptable properties

**Comment by gisIdea** [comment]
Hi i get some levels map tiles . for example 6/52/24.jpg and "6" is a folder name. In my PC,i can use openlayers and its tilelayer and XYZ classes open the local tiles map .but i use vue ，only online map url can show map .how to use local images folder ?

**Comment by gisIdea** [comment]
var BaseMapLayer = function(options) {
var mapExtent = [114.94835, 38.66765, 117.99815, 41.13703];
var layer = new TileLayer({
  extent: Proj.transformExtent(mapExtent, "EPSG:4326", "EPSG:3857"),
  source: new XYZ({
	url: options.url,
	tilePixelRatio: 1,
	minZoom:10,
	maxZoom:15
  })
});
return layer;
};

//定义视图
var view = new View({
	center: Proj.fromLonLat([116.38760, 39.91834]),
	zoom: 13,
	minZoom: 10,
	maxZoom: 15
});

var sateliteopt = {
	url: '../images/cache/satellite/13/6744/3103.jpg'
	//url: require('../images/cache/satellite/{z}/{x}/{y}.jpg')
	//url: require("../images/cache/satellite/13/6744/3103.jpg")
	//url: "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
};

var sateliteLayer = new BaseMapLayer(sateliteopt);

var map = new Map({
	controls: [],
	view: view,
	target: 'map_div'
});
map.addLayer(sateliteLayer);


The code is my projects code
The map local tiles XYZ path is relative path .but can't open the map .please help me.thanks

**Comment by ghettovoice** [comment]
Hi @gisIdea,
as I know , browser by default doesn't allow access to the local file system from canvas. You can try to use absolute path like that `file://path/to/images/{z}/{x}/{y}.jpg` but probably it shouldn't work with canvas. 
May be you should ask about local folder support on the OpenLayers official repository, because if it is supported by OpenLayers then VueLayers should also support it.

The easiest way is setup local web server and provided your local folder to it.
Then you can you custom url pattern `/images/cache/satellite/{z}/{x}/{y}.jpg` with `ol.source.XYZ` (with OpenLayers) or `vl-source-xyz` (with VueLayers)

**Comment by gisIdea** [comment]
Ok thanks it works
